<?php

namespace ContainerQkGAvWC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TQoIEjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tQoI_ej' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tQoI_ej'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'game' => ['privates', '.errored..service_locator.tQoI_ej.App\\Entity\\Games', NULL, 'Cannot autowire service ".service_locator.tQoI_ej": it references class "App\\Entity\\Games" but no such service exists.'],
        ], [
            'em' => '?',
            'game' => 'App\\Entity\\Games',
        ]);
    }
}
