<?php

namespace ContainerQkGAvWC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGamesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tQoI_ej.App\Entity\Games' shared service.
     *
     * @return \App\Entity\Games
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tQoI_ej": it references class "App\\Entity\\Games" but no such service exists.');
    }
}
