<?php

namespace ContainerEBDxg6x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BLNh1YHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BLNh1YH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BLNh1YH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gamesRepository' => ['privates', 'App\\Repository\\GamesRepository', 'getGamesRepositoryService', true],
        ], [
            'em' => '?',
            'gamesRepository' => 'App\\Repository\\GamesRepository',
        ]);
    }
}
