<?php

namespace ContainerCjbstBF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5SlMEqGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5SlMEqG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5SlMEqG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
            'em' => ['privates', '.errored..service_locator.5SlMEqG.Doctrine\\ORM\\EntityManager', NULL, 'Cannot autowire service ".service_locator.5SlMEqG": it references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'],
        ], [
            'client' => '?',
            'em' => 'Doctrine\\ORM\\EntityManager',
        ]);
    }
}
