<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEBDxg6x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEBDxg6x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEBDxg6x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEBDxg6x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEBDxg6x\App_KernelDevDebugContainer([
    'container.build_hash' => 'EBDxg6x',
    'container.build_id' => '03d4c06d',
    'container.build_time' => 1699883269,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEBDxg6x');
