<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLx6jxM8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLx6jxM8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLx6jxM8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLx6jxM8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLx6jxM8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lx6jxM8',
    'container.build_id' => 'f17e5a8d',
    'container.build_time' => 1699625949,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLx6jxM8');
