<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR1OceLy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR1OceLy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR1OceLy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR1OceLy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR1OceLy\App_KernelDevDebugContainer([
    'container.build_hash' => 'R1OceLy',
    'container.build_id' => '18caf50a',
    'container.build_time' => 1699871931,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR1OceLy');
